name: SimpleInventarEdit
main: dev.yourserver.simpleinventaredit.SimpleInventarEditPlugin
version: 2.2.0
api-version: '1.20'
author: JobbeDeluxe
commands:
  sie:
    description: Öffnet das SimpleInventarEdit GUI
    permission: sie.use
permissions:
  sie.use:
    default: op
